import 'package:flutter/material.dart';
import 'package:plainscan/core/constants/app_colors.dart';

class ToolModel {
  final String id;
  final String slug;
  final String name;
  final IconData icon;
  final Color color;
  final String categoryId;
  final String? category;
  final String? inputFormat;
  final String? outputFormat;
  final bool isMultiFile;
  final bool isTextAllowed;
  final bool? isFree;
  final String? description;

  const ToolModel({
    required this.id,
    String? slug,
    required this.name,
    required this.icon,
    required this.color,
    required this.categoryId,
    this.category,
    this.inputFormat,
    this.outputFormat,
    this.isMultiFile = false,
    this.isTextAllowed = false,
    this.isFree = true,
    this.description,
  }) : slug = slug ?? id;
}

const List<ToolModel> allPlainscanTools = [
  // ==========================================
  // 1. 📄 PDF CONVERSION TOOLS
  // ==========================================
  ToolModel(
    id: 'pdf-to-word',
    name: 'PDF to Word',
    icon: Icons.description_outlined,
    color: AppColors.blue,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.docx',
    description: 'Convert PDF files to editable Microsoft Word (.docx) documents.',
  ),
  ToolModel(
    id: 'word-to-pdf',
    name: 'Word to PDF',
    icon: Icons.article_outlined,
    color: AppColors.blue,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.docx / .doc',
    outputFormat: '.pdf',
    description: 'Convert Microsoft Word documents (.docx/.doc) into PDF format.',
  ),
  ToolModel(
    id: 'pdf-to-ppt',
    slug: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    icon: Icons.slideshow_outlined,
    color: AppColors.coral,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.pptx',
    description: 'Convert PDF presentations into editable PowerPoint (.pptx) slides.',
  ),
  ToolModel(
    id: 'ppt-to-pdf',
    slug: 'ppt-to-pdf',
    name: 'PowerPoint to PDF',
    icon: Icons.present_to_all_outlined,
    color: AppColors.coral,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pptx',
    outputFormat: '.pdf',
    description: 'Convert PowerPoint (.pptx) slide decks to standard PDF format.',
  ),
  ToolModel(
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    icon: Icons.table_chart_outlined,
    color: Color(0xFF10B981),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.xlsx',
    description: 'Extract tables and data from PDF into Microsoft Excel (.xlsx).',
  ),
  ToolModel(
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    icon: Icons.grid_on_outlined,
    color: Color(0xFF10B981),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.xlsx / .xls',
    outputFormat: '.pdf',
    description: 'Convert Excel spreadsheets (.xlsx/.xls) into PDF documents.',
  ),
  ToolModel(
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    icon: Icons.image_outlined,
    color: AppColors.amber,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.zip (JPG)',
    description: 'Convert PDF pages into high quality JPG image files in a ZIP archive.',
  ),
  ToolModel(
    id: 'pdf-to-png',
    name: 'PDF to PNG',
    icon: Icons.photo_outlined,
    color: AppColors.amber,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.zip (PNG)',
    description: 'Extract and convert PDF pages into transparent PNG images.',
  ),
  ToolModel(
    id: 'pdf-to-webp',
    name: 'PDF to WebP',
    icon: Icons.perm_media_outlined,
    color: AppColors.amber,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.zip (WebP)',
    description: 'Convert PDF document pages to modern, lightweight WebP image files.',
  ),
  ToolModel(
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    icon: Icons.photo_size_select_actual_outlined,
    color: AppColors.purple,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: 'image (.jpg)',
    outputFormat: '.pdf',
    isMultiFile: true,
    description: 'Convert single or multiple JPG images into a clean PDF document.',
  ),
  ToolModel(
    id: 'png-to-pdf',
    name: 'PNG to PDF',
    icon: Icons.filter_hdr_outlined,
    color: AppColors.purple,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: 'image (.png)',
    outputFormat: '.pdf',
    isMultiFile: true,
    description: 'Convert PNG images with layout sizing into a formatted PDF file.',
  ),
  ToolModel(
    id: 'webp-to-pdf',
    name: 'WebP to PDF',
    icon: Icons.collections_outlined,
    color: AppColors.purple,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: 'image (.webp)',
    outputFormat: '.pdf',
    isMultiFile: true,
    description: 'Convert WebP image files into a single PDF document.',
  ),
  ToolModel(
    id: 'epub-to-pdf',
    name: 'EPUB to PDF',
    icon: Icons.menu_book_outlined,
    color: Color(0xFF0EA5E9),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.epub',
    outputFormat: '.pdf',
    description: 'Convert EPUB e-books into printable, formatted PDF documents.',
  ),
  ToolModel(
    id: 'pdf-to-epub',
    name: 'PDF to EPUB',
    icon: Icons.book_outlined,
    color: Color(0xFF0EA5E9),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.epub',
    isFree: false,
    description: 'Convert PDF documents into responsive EPUB e-reader files.',
  ),
  ToolModel(
    id: 'pdf-to-text',
    name: 'PDF to Text',
    icon: Icons.text_snippet_outlined,
    color: Color(0xFF64748B),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.txt',
    description: 'Extract raw text strings from PDF documents into plain .txt format.',
  ),
  ToolModel(
    id: 'pdf-to-markdown',
    name: 'PDF to Markdown',
    icon: Icons.code_outlined,
    color: Color(0xFF334155),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.pdf',
    outputFormat: '.md',
    description: 'Convert PDF formatted contents and headings into Markdown (.md).',
  ),
  ToolModel(
    id: 'html-to-pdf',
    slug: 'html-to-pdf',
    name: 'HTML to PDF',
    icon: Icons.html_outlined,
    color: Color(0xFFE44D26),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: 'URL / HTML',
    outputFormat: '.pdf',
    description: 'Convert webpage URLs or raw HTML strings into high-quality PDF documents.',
  ),
  ToolModel(
    id: 'images-to-pdf',
    slug: 'images-to-pdf',
    name: 'Images to PDF',
    icon: Icons.collections_outlined,
    color: AppColors.purple,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: 'Multiple images',
    outputFormat: '.pdf',
    isMultiFile: true,
    description: 'Combine multiple image files into a single formatted PDF document.',
  ),
  ToolModel(
    id: 'convert-image',
    slug: 'convert-image',
    name: 'Convert Image',
    icon: Icons.transform_outlined,
    color: AppColors.amber,
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.jpg / .png / .heic / .tiff',
    outputFormat: '.jpg / .png',
    description: 'Convert images between JPG, PNG, HEIC, and TIFF with custom quality.',
  ),
  ToolModel(
    id: 'csv-to-excel',
    slug: 'csv-to-excel',
    name: 'CSV to Excel',
    icon: Icons.table_view_outlined,
    color: Color(0xFF10B981),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.csv',
    outputFormat: '.xlsx',
    description: 'Convert comma- or custom-delimited CSV data files into Excel spreadsheets.',
  ),
  ToolModel(
    id: 'excel-to-csv',
    slug: 'excel-to-csv',
    name: 'Excel to CSV',
    icon: Icons.grid_on_outlined,
    color: Color(0xFF16A34A),
    categoryId: 'conversion',
    category: 'PDF Conversion',
    inputFormat: '.xlsx / .xls',
    outputFormat: '.csv',
    description: 'Convert Excel workbook sheets (.xlsx/.xls) into standard delimited CSV files.',
  ),

  // ==========================================
  // 2. 🛠️ PDF MANIPULATION TOOLS
  // ==========================================
  ToolModel(
    id: 'pdf-compress',
    name: 'PDF Compress',
    icon: Icons.compress_outlined,
    color: Color(0xFF10B981),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Reduce file size while preserving high visual quality.',
  ),
  ToolModel(
    id: 'pdf-merge',
    name: 'PDF Merge',
    icon: Icons.merge_type_outlined,
    color: AppColors.primary,
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: 'Multiple .pdf',
    outputFormat: '.pdf',
    isMultiFile: true,
    description: 'Combine multiple PDF files in your preferred sequence into one PDF.',
  ),
  ToolModel(
    id: 'pdf-split',
    name: 'PDF Split',
    icon: Icons.call_split_outlined,
    color: AppColors.coral,
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.zip',
    description: 'Split a large PDF file into individual pages or page batches.',
  ),
  ToolModel(
    id: 'pdf-rotate',
    name: 'PDF Rotate',
    icon: Icons.rotate_right_outlined,
    color: AppColors.blue,
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Rotate PDF pages by 90°, 180°, or 270° clockwise or counter-clockwise.',
  ),
  ToolModel(
    id: 'pdf-reorder',
    slug: 'pdf-reorder',
    name: 'PDF Reorder / Rearrange',
    icon: Icons.swap_vert_outlined,
    color: AppColors.purple,
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Rearrange and change the order of pages inside your PDF document.',
  ),
  ToolModel(
    id: 'pdf-watermark',
    name: 'PDF Watermark',
    icon: Icons.branding_watermark_outlined,
    color: Color(0xFFD97706),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Add customized text or image stamps, branding, and confidential watermarks.',
  ),
  ToolModel(
    id: 'pdf-lock',
    name: 'PDF Lock (Password Protect)',
    icon: Icons.lock_outline,
    color: Color(0xFFEF4444),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Encrypt and password protect your PDF with 128/256-bit security permissions.',
  ),
  ToolModel(
    id: 'pdf-unlock',
    name: 'PDF Unlock (Remove Password)',
    icon: Icons.lock_open_outlined,
    color: Color(0xFF10B981),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf (locked)',
    outputFormat: '.pdf',
    description: 'Remove password and encryption from password-protected PDF files.',
  ),

  ToolModel(
    id: 'pdf-header-footer',
    name: 'PDF Header & Footer',
    icon: Icons.vertical_align_top_outlined,
    color: Color(0xFF6366F1),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Add customized repeating headers and footers with dynamic page numbering.',
  ),
  ToolModel(
    id: 'pdf-page-numbers',
    name: 'PDF Page Numbers',
    icon: Icons.format_list_numbered_outlined,
    color: Color(0xFF0284C7),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Insert sequential page numbers with custom positions and formatting.',
  ),
  ToolModel(
    id: 'pdf-sign',
    name: 'PDF Sign / E-Sign',
    icon: Icons.draw_outlined,
    color: Color(0xFFEC4899),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Digitally sign PDF contracts, documents, and agreements.',
  ),
  ToolModel(
    id: 'pdf-compare',
    name: 'PDF Compare',
    icon: Icons.compare_arrows_outlined,
    color: Color(0xFF8B5CF6),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '2 .pdf files',
    outputFormat: '.pdf (diff report)',
    isMultiFile: true,
    isFree: false,
    description: 'Compare two PDF documents side-by-side with color-coded diff highlights.',
  ),
  ToolModel(
    id: 'form-filling',
    slug: 'form-filling',
    name: 'PDF Form Filling',
    icon: Icons.assignment_turned_in_outlined,
    color: Color(0xFF059669),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf (form)',
    outputFormat: '.pdf',
    isFree: false,
    description: 'Automatically fill out interactive PDF forms using structured field data.',
  ),
  ToolModel(
    id: 'pdf-to-fillable-form',
    slug: 'pdf-to-fillable-form',
    name: 'PDF to Fillable Form',
    icon: Icons.dynamic_form_outlined,
    color: Color(0xFF0D9488),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    isFree: false,
    description: 'Auto-detect lines and boxes in standard PDFs to generate interactive fillable forms.',
  ),
  ToolModel(
    id: 'pdf-extract-text',
    name: 'PDF Extract Text',
    icon: Icons.text_fields_outlined,
    color: Color(0xFF475569),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.txt',
    description: 'Extract all textual content from PDF files for editing and indexing.',
  ),
  ToolModel(
    id: 'pdf-extract-table',
    name: 'PDF Extract Tables',
    icon: Icons.table_view_outlined,
    color: Color(0xFF16A34A),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.xlsx',
    description: 'Parse, detect and export PDF tabular records directly to Excel sheets.',
  ),
  ToolModel(
    id: 'pdf-extract-images',
    name: 'PDF Extract Images',
    icon: Icons.photo_library_outlined,
    color: Color(0xFFEA580C),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.zip',
    description: 'Extract all embedded graphics and photos from PDF into a ZIP archive.',
  ),
  ToolModel(
    id: 'flatten-pdf',
    slug: 'flatten-pdf',
    name: 'Flatten PDF',
    icon: Icons.layers_clear_outlined,
    color: Color(0xFF64748B),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Flatten form fields, annotations, and markup layers permanently into static PDF pages.',
  ),
  ToolModel(
    id: 'n-up-pdf',
    slug: 'n-up-pdf',
    name: 'N-up PDF',
    icon: Icons.view_quilt_outlined,
    color: Color(0xFF8B5CF6),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Combine multiple PDF pages (2, 4, 6, 9) onto each printed sheet to save paper.',
  ),
  ToolModel(
    id: 'pdf-to-grayscale',
    slug: 'pdf-to-grayscale',
    name: 'PDF to Grayscale',
    icon: Icons.filter_b_and_w_outlined,
    color: Color(0xFF475569),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Convert full-color PDF documents into pure black and white grayscale to reduce printer ink.',
  ),
  ToolModel(
    id: 'print-optimize-pdf',
    slug: 'print-optimize-pdf',
    name: 'Print Optimize PDF',
    icon: Icons.print_outlined,
    color: Color(0xFF0284C7),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Downsample high-resolution images to drastically reduce PDF file size for rapid printing.',
  ),
  ToolModel(
    id: 'repair-pdf',
    slug: 'repair-pdf',
    name: 'Repair PDF',
    icon: Icons.healing_outlined,
    color: Color(0xFFEF4444),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf (damaged)',
    outputFormat: '.pdf',
    description: 'Analyze and rebuild corrupted or unreadable PDF document headers and cross-reference tables.',
  ),
  ToolModel(
    id: 'crop-pdf',
    slug: 'crop-pdf',
    name: 'Crop PDF',
    icon: Icons.crop_outlined,
    color: Color(0xFF0D9488),
    categoryId: 'manipulation',
    category: 'PDF Manipulation',
    inputFormat: '.pdf',
    outputFormat: '.pdf',
    description: 'Trim unwanted page margins, white borders, and headers off PDF documents.',
  ),

  // ==========================================
  // 3. 🔍 OCR / SCAN TOOLS
  // ==========================================
  ToolModel(
    id: 'scan-ocr',
    slug: 'scan-ocr',
    name: 'Scan / OCR to Text',
    icon: Icons.document_scanner_outlined,
    color: AppColors.primary,
    categoryId: 'ocr',
    category: 'OCR / Scan Tools',
    inputFormat: '.pdf / image',
    outputFormat: '.txt',
    description: 'Perform high-accuracy optical character recognition in multiple languages.',
  ),
  ToolModel(
    id: 'ocr-to-pdf',
    name: 'OCR to PDF (Searchable PDF)',
    icon: Icons.find_in_page_outlined,
    color: AppColors.blue,
    categoryId: 'ocr',
    category: 'OCR / Scan Tools',
    inputFormat: '.pdf (scanned)',
    outputFormat: '.pdf',
    isFree: false,
    description: 'Convert scanned image PDFs into fully searchable, selectable PDF documents.',
  ),
  ToolModel(
    id: 'ocr-to-word',
    name: 'OCR to Word',
    icon: Icons.file_present_outlined,
    color: AppColors.blue,
    categoryId: 'ocr',
    category: 'OCR / Scan Tools',
    inputFormat: '.pdf / image',
    outputFormat: '.docx',
    isFree: false,
    description: 'Recognize scanned document text and reconstruct into formatted Word DOCX.',
  ),
  ToolModel(
    id: 'ocr-to-excel',
    name: 'OCR to Excel',
    icon: Icons.receipt_long_outlined,
    color: Color(0xFF10B981),
    categoryId: 'ocr',
    category: 'OCR / Scan Tools',
    inputFormat: '.pdf / image',
    outputFormat: '.xlsx',
    isFree: false,
    description: 'Extract scanned receipts, invoices, and tables into organized Excel spreadsheets.',
  ),

  // ==========================================
  // 4. 🤖 AI TOOLS
  // ==========================================
  ToolModel(
    id: 'ai-summarize',
    name: 'AI Summarize',
    icon: Icons.summarize_outlined,
    color: Color(0xFF6366F1),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.txt',
    isTextAllowed: true,
    isFree: false,
    description: 'Generate concise, medium, or detailed AI executive summaries of documents.',
  ),
  ToolModel(
    id: 'ai-rewrite',
    name: 'AI Rewrite',
    icon: Icons.edit_note_outlined,
    color: Color(0xFF8B5CF6),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.docx',
    isTextAllowed: true,
    isFree: false,
    description: 'Rewrite and improve text with Professional, Casual, Formal, or Academic styles.',
  ),
  ToolModel(
    id: 'ai-translate',
    name: 'AI Translate',
    icon: Icons.g_translate_outlined,
    color: Color(0xFF0284C7),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.docx',
    isTextAllowed: true,
    isFree: false,
    description: 'Translate documents and text into Spanish, French, German, Hindi, Arabic, etc.',
  ),
  ToolModel(
    id: 'ai-extract-data',
    slug: 'ai-extract-data',
    name: 'AI Extract Data',
    icon: Icons.data_object_outlined,
    color: Color(0xFF059669),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.json',
    isTextAllowed: true,
    isFree: false,
    description: 'Extract specified custom fields (invoice #, total, vendor, date) into JSON data.',
  ),
  ToolModel(
    id: 'ai-extract-key-points',
    slug: 'ai-extract-key-points',
    name: 'AI Extract Key Points',
    icon: Icons.checklist_outlined,
    color: Color(0xFFD97706),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.txt',
    isTextAllowed: true,
    isFree: false,
    description: 'Extract action items, key takeaways, and core bullet points automatically.',
  ),
  ToolModel(
    id: 'ai-expand',
    name: 'AI Expand Text',
    icon: Icons.unfold_more_outlined,
    color: Color(0xFF9333EA),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.docx',
    isTextAllowed: true,
    isFree: false,
    description: 'Elaborate and expand concise notes or draft outlines into full documents.',
  ),
  ToolModel(
    id: 'ai-condense',
    name: 'AI Condense Text',
    icon: Icons.unfold_less_outlined,
    color: Color(0xFF7C3AED),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.docx',
    isTextAllowed: true,
    isFree: false,
    description: 'Condense long paragraphs into brief, high-impact statements.',
  ),
  ToolModel(
    id: 'ai-keywords',
    name: 'AI Keywords / SEO Tags',
    icon: Icons.label_important_outline,
    color: Color(0xFF2563EB),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.json',
    isTextAllowed: true,
    isFree: false,
    description: 'Extract search tags, keywords, and SEO metadata from your content.',
  ),
  ToolModel(
    id: 'grammar-checker',
    slug: 'grammar-checker',
    name: 'Grammar Checker / Correction',
    icon: Icons.spellcheck_outlined,
    color: Color(0xFF10B981),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / text',
    outputFormat: '.docx',
    isTextAllowed: true,
    isFree: false,
    description: 'Check grammar, spelling, punctuation and syntax corrections instantly.',
  ),
  ToolModel(
    id: 'humanize-ai-content',
    slug: 'humanize-ai-content',
    name: 'AI Humanize Content',
    icon: Icons.face_retouching_natural_outlined,
    color: Color(0xFFEC4899),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / text',
    outputFormat: '.docx',
    isTextAllowed: true,
    isFree: false,
    description: 'Make AI generated text sound more natural, expressive, and human-written.',
  ),
  ToolModel(
    id: 'ai-detector',
    slug: 'ai-detector',
    name: 'AI Detector (Content Detection)',
    icon: Icons.psychology_outlined,
    color: Color(0xFFDC2626),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / text',
    outputFormat: '.json',
    isTextAllowed: true,
    isFree: false,
    description: 'Analyze documents to detect whether content was generated by AI models.',
  ),
  ToolModel(
    id: 'plagiarism-check',
    name: 'Plagiarism Check',
    icon: Icons.policy_outlined,
    color: Color(0xFFB45309),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / text',
    outputFormat: '.pdf (report)',
    isTextAllowed: true,
    isFree: false,
    description: 'Scan content against web and publication databases to produce a plagiarism report.',
  ),
  ToolModel(
    id: 'summarize-long-pdfs',
    slug: 'summarize-long-pdfs',
    name: 'AI Summarize Long PDF',
    icon: Icons.menu_book_outlined,
    color: Color(0xFF4F46E5),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf',
    outputFormat: '.txt',
    isFree: false,
    description: 'Handle massive multi-chapter books, research papers, and lengthy PDFs.',
  ),
  ToolModel(
    id: 'ai-resume-formatter',
    name: 'AI Resume Formatter',
    icon: Icons.contact_page_outlined,
    color: Color(0xFF0284C7),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx',
    outputFormat: '.docx',
    isFree: false,
    description: 'Reformat and enhance resumes for maximum ATS compatibility.',
  ),
  ToolModel(
    id: 'ai-cover-letter',
    name: 'AI Cover Letter Generator',
    icon: Icons.mark_email_read_outlined,
    color: Color(0xFF059669),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx (resume)',
    outputFormat: '.docx',
    isFree: false,
    description: 'Generate customized cover letters tailored directly to specific job descriptions.',
  ),
  ToolModel(
    id: 'bank-statement-to-excel',
    slug: 'bank-statement-to-excel',
    name: 'Bank Statement to Excel',
    icon: Icons.account_balance_outlined,
    color: Color(0xFF059669),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf',
    outputFormat: '.xlsx',
    isFree: false,
    description: 'AI-powered extraction of transaction tables and balances from bank statement PDFs into Excel.',
  ),
  ToolModel(
    id: 'receipt-to-excel',
    slug: 'receipt-to-excel',
    name: 'Receipt to Excel',
    icon: Icons.receipt_long_outlined,
    color: Color(0xFFD97706),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / image',
    outputFormat: '.xlsx',
    isFree: false,
    description: 'AI-powered parsing of receipt and invoice details into structured Excel spreadsheets.',
  ),
  ToolModel(
    id: 'ai-email-writer',
    slug: 'ai-email-writer',
    name: 'AI Email Writer',
    icon: Icons.email_outlined,
    color: Color(0xFF2563EB),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: 'Text & Subject',
    outputFormat: '.txt',
    isFree: false,
    description: 'Generate tailored professional, casual, or friendly emails with AI.',
  ),
  ToolModel(
    id: 'ai-proofread',
    slug: 'ai-proofread',
    name: 'AI Proofread',
    icon: Icons.spellcheck_outlined,
    color: Color(0xFF059669),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx / text',
    outputFormat: '.docx',
    isTextAllowed: true,
    isFree: false,
    description: 'Proofread and refine grammar, tone, clarity, and phrasing in your writing.',
  ),
  ToolModel(
    id: 'ai-citation',
    slug: 'ai-citation',
    name: 'AI Citation Generator',
    icon: Icons.format_quote_outlined,
    color: Color(0xFF7C3AED),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: 'Source text',
    outputFormat: '.txt',
    isFree: false,
    description: 'Format accurate citations in APA, MLA, Chicago, or Harvard styles.',
  ),
  ToolModel(
    id: 'ai-flashcards',
    slug: 'ai-flashcards',
    name: 'AI Flashcards',
    icon: Icons.style_outlined,
    color: Color(0xFFEA580C),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / text',
    outputFormat: '.json',
    isTextAllowed: true,
    isFree: false,
    description: 'Generate study flashcard Q&A decks from uploaded documents or text.',
  ),
  ToolModel(
    id: 'ai-quiz',
    slug: 'ai-quiz',
    name: 'AI Quiz Generator',
    icon: Icons.quiz_outlined,
    color: Color(0xFFD97706),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / text',
    outputFormat: '.json',
    isTextAllowed: true,
    isFree: false,
    description: 'Generate multiple-choice or short-answer quiz questions by difficulty level.',
  ),
  ToolModel(
    id: 'chat-with-pdf',
    slug: 'chat-with-pdf',
    name: 'Chat with PDF',
    icon: Icons.chat_outlined,
    color: Color(0xFF0284C7),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf',
    outputFormat: '.txt',
    isFree: false,
    description: 'Ask questions, query facts, and chat interactively with your PDF documents.',
  ),
  ToolModel(
    id: 'ats-scanner',
    slug: 'ats-scanner',
    name: 'ATS Resume Scanner',
    icon: Icons.fact_check_outlined,
    color: Color(0xFF10B981),
    categoryId: 'ai',
    category: 'AI Tools',
    inputFormat: '.pdf / .docx',
    outputFormat: '.json',
    isFree: false,
    description: 'Analyze resumes for ATS parsing compliance and match against job descriptions.',
  ),

  // ==========================================
  // 5. 📦 UTILITY TOOLS
  // ==========================================
  ToolModel(
    id: 'file-to-zip',
    name: 'File to ZIP',
    icon: Icons.folder_zip_outlined,
    color: Color(0xFFD97706),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Multiple files',
    outputFormat: '.zip',
    isMultiFile: true,
    description: 'Bundle multiple files and documents into a compressed .zip archive.',
  ),
  ToolModel(
    id: 'batch-pdf-converter',
    slug: 'batch-pdf-converter',
    name: 'Batch Converter',
    icon: Icons.published_with_changes_outlined,
    color: AppColors.primary,
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Multiple files',
    outputFormat: '.zip',
    isMultiFile: true,
    isFree: false,
    description: 'Convert a batch of files simultaneously to Word, PDF, or TXT format.',
  ),
  ToolModel(
    id: 'batch-rename',
    name: 'Batch Rename',
    icon: Icons.drive_file_rename_outline,
    color: Color(0xFF475569),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Multiple files',
    outputFormat: '.zip',
    isMultiFile: true,
    description: 'Rename multiple files in bulk with prefixes, suffixes, replacement rules, and numbers.',
  ),
  ToolModel(
    id: 'id-templates',
    slug: 'id-templates',
    name: 'ID Templates',
    icon: Icons.badge_outlined,
    color: Color(0xFF3B82F6),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Form & Photos',
    outputFormat: '.pdf',
    description: 'Generate high-resolution corporate, student, or membership ID card PDFs with custom logos and photos.',
  ),
  ToolModel(
    id: 'invoice-generator',
    slug: 'invoice-generator',
    name: 'Invoice Generator',
    icon: Icons.receipt_outlined,
    color: Color(0xFF4F46E5),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Form data',
    outputFormat: '.pdf',
    description: 'Generate professional invoice PDFs with line items, tax rates, discounts, and custom branding.',
  ),
  ToolModel(
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word Counter',
    icon: Icons.pin_outlined,
    color: Color(0xFF475569),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Text',
    outputFormat: '.txt',
    description: 'Accurately count words, reading time, and paragraph density in your text.',
  ),
  ToolModel(
    id: 'character-counter',
    slug: 'character-counter',
    name: 'Character Counter',
    icon: Icons.text_fields_outlined,
    color: Color(0xFF64748B),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Text',
    outputFormat: '.txt',
    description: 'Count characters with and without spaces for essays, tweets, and metadata.',
  ),
  ToolModel(
    id: 'image-to-base64',
    slug: 'image-to-base64',
    name: 'Image to Base64',
    icon: Icons.data_object_outlined,
    color: Color(0xFF059669),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Image (.jpg/.png)',
    outputFormat: '.txt',
    description: 'Encode any image file into a clean data URI Base64 string for web usage.',
  ),
  ToolModel(
    id: 'base64-to-image',
    slug: 'base64-to-image',
    name: 'Base64 to Image',
    icon: Icons.image_outlined,
    color: Color(0xFF2563EB),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Base64 string',
    outputFormat: '.png',
    description: 'Decode Base64 raw strings and data URIs back into high-quality images.',
  ),
  ToolModel(
    id: 'favicon-generator',
    slug: 'favicon-generator',
    name: 'Favicon Generator',
    icon: Icons.web_outlined,
    color: Color(0xFFD97706),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: 'Square PNG / JPG',
    outputFormat: '.ico',
    description: 'Generate standard website favicon assets and icons from square photos.',
  ),
  ToolModel(
    id: 'metadata-editor',
    slug: 'metadata-editor',
    name: 'Metadata Editor',
    icon: Icons.edit_note_outlined,
    color: Color(0xFF7C3AED),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: '.pdf / Image',
    outputFormat: '.jpg',
    description: 'View or strip EXIF and sensitive location metadata from image files.',
  ),
  ToolModel(
    id: 'remove-metadata',
    slug: 'remove-metadata',
    name: 'Remove Metadata',
    icon: Icons.phonelink_erase_outlined,
    color: Color(0xFFEF4444),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: '.pdf / Image',
    outputFormat: '.pdf',
    description: 'Strip author, GPS coordinates, camera tags, and hidden metadata from PDFs and images.',
  ),
  ToolModel(
    id: 'read-metadata',
    slug: 'read-metadata',
    name: 'Read Metadata',
    icon: Icons.info_outline,
    color: Color(0xFF0284C7),
    categoryId: 'utility',
    category: 'Utility Tools',
    inputFormat: '.pdf / Image',
    outputFormat: '.txt',
    description: 'Inspect embedded document attributes, creation dates, camera specifications, and tags.',
  ),
];