// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCub71VYqaz6NdFtdq7WOgiJLxSqN8BIjg',
    appId: '1:690500109578:web:3038d9391e0ba7c963e6f3',
    messagingSenderId: '690500109578',
    projectId: 'plainscan-54b66',
    authDomain: 'plainscan-54b66.firebaseapp.com',
    storageBucket: 'plainscan-54b66.firebasestorage.app',
    measurementId: 'G-P9PSTGNT1H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAj572xVMBVD4gTOTPO40vt-oOGDSfVQ4g',
    appId: '1:690500109578:android:e9e4449f9254d4c663e6f3',
    messagingSenderId: '690500109578',
    projectId: 'plainscan-54b66',
    storageBucket: 'plainscan-54b66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBas9F4XLDRZYi3tUUAyOoaiVpvqXbA3VQ',
    appId: '1:690500109578:ios:1d1d28940ed7026e63e6f3',
    messagingSenderId: '690500109578',
    projectId: 'plainscan-54b66',
    storageBucket: 'plainscan-54b66.firebasestorage.app',
    androidClientId: '690500109578-ojt7n2f6pbf6im3d7prb2adom37gfus3.apps.googleusercontent.com',
    iosBundleId: 'com.plainscan.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBas9F4XLDRZYi3tUUAyOoaiVpvqXbA3VQ',
    appId: '1:690500109578:ios:1d1d28940ed7026e63e6f3',
    messagingSenderId: '690500109578',
    projectId: 'plainscan-54b66',
    storageBucket: 'plainscan-54b66.firebasestorage.app',
    androidClientId: '690500109578-ojt7n2f6pbf6im3d7prb2adom37gfus3.apps.googleusercontent.com',
    iosBundleId: 'com.plainscan.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCub71VYqaz6NdFtdq7WOgiJLxSqN8BIjg',
    appId: '1:690500109578:web:a0988b0ff7429e8f63e6f3',
    messagingSenderId: '690500109578',
    projectId: 'plainscan-54b66',
    authDomain: 'plainscan-54b66.firebaseapp.com',
    storageBucket: 'plainscan-54b66.firebasestorage.app',
    measurementId: 'G-CVDQ60M4PN',
  );
}
